version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  test-runner:
    build:
      context: .
    depends_on:
      - grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    environment:
      GRAFANA_BASE_URL: http://grafana:3000
      GRAFANA_DB_PATH: /var/lib/grafana/grafana.db
    command: >
      sh -c "
      echo '⏳ Waiting for Grafana...';
      for i in {1..30}; do
        if curl -s http://grafana:3000/api/health | grep -q '\"database\":\"ok\"'; then
          echo '✅ Grafana is up';
          break;
        fi
        echo 'Still waiting...';
        sleep 2;
      done;
      pytest /app/tests --alluredir=/app/allure-results
      "

volumes:
  grafana-data:
