services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - my-net
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  test-runner:
    build:
      context: .
    volumes:
      - grafana-data:/var/lib/grafana
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    networks:
      - my-net
    environment:
      GRAFANA_DB_PATH: /var/lib/grafana/grafana.db
      GRAFANA_BASE_URL: http://grafana:3000
    command: pytest /app/tests --alluredir=/app/allure-results

volumes:
  grafana-data:

networks:
  my-net:
