permissions:
  contents: write
  actions: read

name: Run PyTests
on:
  workflow_dispatch:

# Setup Grafana from Docker
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    services:
      grafana:
        image: grafana/grafana:latest
        ports:
          - 3000:3000
        options: >-
          --env GF_SECURITY_ADMIN_PASSWORD=admin
          --env GF_SECURITY_ADMIN_USER=admin

    steps:
      # Check code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Setup dependencies
      - name: Install dependencies
        run: pip install pytest

      # Setup requests
      - name: Install requests
        run: pip install requests

      # Setup Allure
      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Setup allure pytest
      - name: Install Allure
        run: pip install allure-pytest

      # Wait grafana starts
      - name: Wait for Grafana
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 | grep "Found"; then
              echo "Grafana is ready!"
              exit 0
            fi
            echo "Waiting for Grafana to start..."
            sleep 2
          done
          echo "Grafana did not start in time!" && exit 1

      # Run PyTest with allure
      - name: Run PyTest tests with Allure
        run:  python -m pytest --alluredir allure-results

      # Restore history from previous report

      - name: Restore history from previous report
        if: always()
        run: |
          if [ -d gh-pages/allure-report/history ]; then
            cp -r gh-pages/allure-report/history allure-results/history
          fi

      # Generate Allure reports
      - name: Generate Allure report
        if: always()
        run:  allure generate allure-results -o allure-report
        continue-on-error: true

      - name: Deploy Allure report to GitHub Pages
        if: always()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          if git ls-remote --exit-code --heads https://github.com/${{ github.repository }} gh-pages; then
            git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          else
            git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
            cd gh-pages
            git checkout --orphan gh-pages
            git rm -rf .
            cd ..
          fi

          cd gh-pages
          rm -rf allure-report
          cp -r ../allure-report ./allure-report
          touch .nojekyll

          git add .
          git commit -m "🚀 Update Allure report"
          git push origin gh-pages